    # aeNormal = AE(test = True, normalVersion=True, modelPath = autoencoderNormPath)
    # aeAbnormal = AE(test = True, normalVersion=False, modelPath = autoencoderAbnormPath)
    # loss_aeNormal_dataAbnormal = aeNormal.test(abnorm_testDataDir)
    # loss_aeAbnormal_dataAbnormal = aeAbnormal.test(abnorm_testDataDir)
    # print(len(loss_aeAbnormal_dataAbnormal))
    # print(len(loss_aeNormal_dataAbnormal))